[project]
name = 'sentinel'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.magnetosphere-monitor]
path = 'contracts/magnetosphere-monitor.clar'
clarity_version = 2
epoch = 2.5

[contracts.sentinel]
path = 'contracts/sentinel.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
